#version 460 core

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (rgba32f, binding=0) uniform image2D imgOutput;

uniform float time;

void main()
{
	vec4 value = vec4(0.f,0.f,0.f,1.f);
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

	float targetInSeconds = 5.f;
	float t = mod(time, targetInSeconds);
	value.r = t / targetInSeconds;

	imageStore(imgOutput,texelCoord,value);
}
